### ISSUE TITLE
Maintainability with Cyclomatic?

### ISSUE THREAD

**Issue by Nikoms** [ytetsuro/sabik#269]
Hi!

I see in the doc that the maintainability index is using "Cognitive" instead of "Cyclomatic" complexity. Do you use cognitive because it's better? Or because "Cyclomatic" is not available in the code yet?

I'd like to have the maintainability based on "Cyclomatic", that's why I'm asking :)

Thank you!

**Comment by ytetsuro** [comment]
@Nikoms 

Hi!
Thanks question!

I think harder to get a good score on the Cognitive.
The Cognitive often scores higher for the exact same chord.
In other words, we thought it would be easier to make good code.☺️

There is no evidence that it is really good code. It is a feeling.😅

I think if there are users who want to change it, I am willing to change it.👍
Please let me know for my learning.
Why do you want to use Cyclomatic?

**Comment by Nikoms** [comment]
Hey! Thanks for your anwser, it's cool!

In fact, I'm looking for a library to have the maintainability index of my projects. There are not so many that works with TS+JS.

To give you the context, I have a file that is really really messy.
- sonar gives it a maintainability score of A, which i don't believe
- sabik is giving a maintainability score of 61,95 (min)/79,44 (avg)
- codehawk is giving a score of zero which the score I would also give 😅


It seems that codehawk is using /typhonjs-node-escomplex ad the computation is here: https://github.com/typhonjs-node-escomplex/escomplex-plugin-metrics-module/blob/7a4ddb6a0def5c90b8aa2f06c3e0867ba10eacd6/src/ModuleMetricPostAverage.js#L45-L49

So I just try to understand the differences here but I don't know if it's because the cognitive/cyclomatic differences

**Comment by ytetsuro** [comment]
@Nikoms

> So I just try to understand the differences here but I don't know if it's because the cognitive/cyclomatic differences

Thank you!
In my opinion, perhaps cognitive/cyclomatic is irrelevant.🤔
This is because I believe that maintainability is lower when measured cognitively than when measured cyclomatic.🤔
I am curious about the following comments.

https://github.com/typhonjs-node-escomplex/escomplex-plugin-metrics-module/blob/81a1e9e20147cc1b6102638524153867b2f9f9b3/src/ModuleMetricPostAverage.js#L54-L56

Even if sabik were not class-based, it would measure maintainability on a per-function basis.👍
There may be a difference here.

I would be glad to know the values of "averageCyclomatic", "averageEffort" and "averageLoc" for the files in question.🙏

https://github.com/typhonjs-node-escomplex/escomplex-plugin-metrics-module/blob/7a4ddb6a0def5c90b8aa2f06c3e0867ba10eacd6/src/ModuleMetricPostAverage.js#L68

Can you also tell me the "halstead", "complexity" and "logicalLineOfCode" of sabik at that time?🙏

https://github.com/ytetsuro/sabik/blob/develop/src/Analyzer/CodeMetricsCalculator/Maintainability/Maintainability.ts#L20

I'll try to get some Cyclomatic Complexity measured on my end!👍
