### ISSUE TITLE
Sub functions within a component sometime missed 

### ISSUE THREAD

**Issue by nimisis** [ytetsuro/sabik#331]
Regression from 0.2.3 to 0.2.4: If I have a component like

```
const Clock = () => {
  ...
  const show = () => {
     ...
  }
}

export default Clock
```

then the subfunction `show()` is ignored and the complexity is significantly higher than if I used the following syntax:

```
export default function Clock() {
   ...
   const show = () => {
      ...
   }
}
```

I think both should result in the same values after analysis.

**Comment by ytetsuro** [comment]
Sorry for the delay in getting back to you.
Thanks for letting me know.
I will investigate and fix.

**Comment by ytetsuro** [comment]
@nimisis 

I have looked into this and it may not be a bug.
Is it the cognitive complexity that you found to be a bug?
If so, there is a distinct difference in the example you submitted.

The latter can be treated as a faux-class in the history of JS, while the former cannot be treated as a faux-class.

See the chapter `JavaScript: Missing class structures` in Cognitive Complexity for specifics. 

> Despite the recent addition of classes to JavaScript by the ECMAScript 6 specification, the feature is not yet widely adopted. In fact, many popular frameworks require the continued use of the compensating idiom: the use of an outer function as a stand-in to create a kind of namespace or faux class. So as not to penalize JavaScript users, such outer functions are ignored when they are used purely as a declarative mechanism, that is when they contain only declarations at the top level.
> However, the presence at the top level of a function (i.e. not nested inside a sub-function) of statements subject to structural increments indicates something other than a pure declarative usage. Consequently, such functions should receive a standard treatment.

Since the arrow function cannot be a pseudo-class, I believe the current implementation is correct. What do you think?

```javascript
new (() => {}) // Uncaught TypeError: (intermediate value) is not a constructor
new (function () {}) // {}
```

**Comment by ytetsuro** [comment]
Again, please let me know if you think this is the problem!
Thank you for your inquiry!
